### ISSUE TITLE
AWS account name with capital letter. 

### ISSUE THREAD

**Issue by mubarak1988** [walery/stencil-aws-account-resolver#1]
Hello :)! I am facing issues when the account name contains a capital letter. e.g. If the account name is Foo-bar. The recommendation for the quick fix is updating in name.js file line 12 to `resolve((Account.Name).toLowerCase());`

**Comment by walery** [comment]
Hello Mubarak,

if the account name is `Foo-bar` then the result should be `Foo-bar`. Following your recommendation result would be `foo-bar` which IMO is wrong (and confusing).

Maybe you can explain in which case you're facing the issue, the it would be easier to understand if something is missing in this plugin.

**Comment by mubarak1988** [comment]
Oh ok, thanks I understand. This is the error I get when I am trying to run the serverless. 
Cannot resolve serverless.yml: Variables resolution errored with:
  - Cannot resolve variable at "provider.deploymentBucket.name": Failed to create bucket with name 'product.us-east-1.bar.Fo.us. The specified bucket is not valid.
  
So since Bucket names can consist only of lowercase letters (https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html) I was thinking of maybe resolving this in the name resolution but it can be handled specifically for the bucket name aswell. So what do you suggest?

**Comment by walery** [comment]
I see what you mean.

Probably the error is coming from this call `${stencil(product-bucket):name}`?

If yes, then this is the wrong repo. The [walery/stencil-product-bucket](https://github.com/walery/stencil-product-bucket) is the one that needs to be fixed.

Can you create the new issue in the correct repo? And PRs are welcome too 😏

**Comment by mubarak1988** [comment]
got it, added! 😄 . Closing this issue from here.

**Comment by walery** [comment]
https://github.com/walery/stencil-product-bucket/pull/1
